### PR TITLE
Add a enabled status to the multiselect

### PR DESCRIPTION
**Pull request by alienriquebm**

### CODE REVIEW

**Comment by aebmknrl** [comment]
Done my friend @cetorres

**Comment by cetorres** [comment]
Please fix the conflict, so I can merge your PR.
Thank you.

**Comment by alienriquebm** [comment]
Done

**Comment by Rouvo** [comment]
Thanks @alienriquebm, I have been looking for this property and found your PR. 
As a little push, since I'm looking forward to use this, can you merge this @cetorres?

**Comment by cetorres** [comment]
Updated to pub.dev. Thanks.

**Pull request merged**
