### PR TITLE
Added max selections variable

### PR DESCRIPTION
**Pull request by JupiterThreads**
I needed to be able to control how many options a user can select before they click ok. In my use case the validation wasn't sufficient because if a user selected quite a few options and they return to my widget, they wouldn't be able see the validation message telling them that they've selected too many options. In my widget I limited the size of the multiselect_formfield so it doesn't take up the whole page. In any event, I think it provides a better user experience if they are only allowed to select a certain number of items over a validation message.

Also fixed no such method error when data source is empty when data source is coming from a future and selected options display where existing item is null.

Set a key to field to prevent flutter from using previous state when initial values are changed. The data I have to display and what is being selected can be changed frequently so I need to wipe prev state.

### CODE REVIEW

**Comment by cetorres** [comment]
Please fix the conflict, so I can merge your PR.
Thank you.

**Comment by JupiterThreads** [comment]
There seems to be a bug somewhere. Every time I make a selection the alert is popping off and the values are not being fed back. I am looking into it.

**Comment by JupiterThreads** [comment]
It seems it was some flutter version build problem. Seems to work fine now.

**Comment by JupiterThreads** [comment]
Are your going to merge this in? I don’t want to fix more conflicts for it to be left. Thanks

**Comment by cetorres** [comment]
Hi @JupiterThreads, please fix the conflict first then I can merge it.
Thanks.

**Pull request closed without merging**
