### PR TITLE
Bugfix: When providing default value on load the validator is always null 

### PR DESCRIPTION
**Pull request by DavidCorrado**
**Bug Report:**
https://github.com/cetorres/multiselect_formfield/issues/9

**Comments for reviewer:**

- I removed all intellij files and .gitignored.  This seems to be recommended.  I also .gitignored some files that were auto generated in my project for iOS.
- Fixed a warning with the validator that said you must always return something.  Returning null is the proper thing to return if passed validation: https://flutter.dev/docs/cookbook/forms/validation
- Made a breaking change.  I removed value.  Seems like its more standard to have initialValue.  I essentially just replaced your value for the built in state.value.  In which initialvalue automatically sets state.value as you can see in https://github.com/flutter/flutter/blob/e0c63cd35e15e407a80dc44281cc392535fcce25/packages/flutter/lib/src/widgets/form.dart#L422

I appreciate your consideration for including.  Thanks for creating this library.

### CODE REVIEW

**Comment by aebmknrl** [comment]
This is very important. We need this fix very very soon!

**Comment by cetorres** [comment]
Thank you, @DavidCorrado!

**Comment by aebmknrl** [comment]
Thanks @DavidCorrado and also thanks to you @cetorres for this great widget. You will publish the update on pub.dev soon?

**Comment by cetorres** [comment]
@aebmknrl I just published it. Thanks.

**Comment by aebmknrl** [comment]
Thanks to you brother. Please when you have some time, check my PR. Thanks

**Comment by cetorres** [comment]
@aebmknrl your PR is with a conflict now. Can you fix it?

**Comment by aebmknrl** [comment]
Yes my friend, i will check it out in a few minutes

**Pull request merged**
